name: publish

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    name: Publish container images

    permissions:
      id-token: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: generate_tag
        run: echo "version=$(cat ./version.md)" >> $GITHUB_OUTPUT

      - name: Login To Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: yunling101/prometheus-config-reloader:${{steps.generate_tag.outputs.version}}
